### ISSUE TITLE
Update SDK version

### ISSUE THREAD

**Issue by TomAFrench** [paulrberg/sablier-safe-app#70]
We're a few versions behind now and the newer versions allow us to track transaction status after we send them. We could probably do something interesting with that.

**Comment by PaulRBerg** [comment]
Can you provide some examples? would we be able to do little enhancements like displaying loaders, or bigger things?

**Comment by paulrberg** [comment]
Implemented in:

- https://github.com/paulrberg/sablier-safe-app/commit/9ba1aaadcdb62a809e5237d63e82aaf1408c50e4
- https://github.com/paulrberg/sablier-safe-app/commit/1363fb2da2a5c99e8f199efeb12c2c5f8cb19527
