### ISSUE TITLE
Please add 'ICHI' to gnosis safe app

### ISSUE THREAD

**Issue by masanobufukuoka** [paulrberg/sablier-safe-app#82]
ICHI contract address: 0x903bEF1736CDdf2A537176cf3C64579C3867A881

ICHI has $7M worth in Sablier Finance - it should be added to gnosis app.  Please help.

**Comment by paulrberg** [comment]
Hey @masanobufukuoka! Sorry for the late reply here. To request a token listing, please reach out to Max on our Discord server:

https://discord.gg/KXajCXC

Thanks for your interest in Sablier!
